# This is a basic workflow to help you get started with Actions

name: CI2

# Controls when the workflow will run
on:
  pull_request:
    types: 
      - closed
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: github.event.pull_request.merged == true
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      # Runs a single command using the runners shell
      - name: Show current branch running workflow manually
        run: echo $GITHUB_REF_NAME